#!/usr/bin/env bash
# Install secrets/age.key on Proxmox VMs via a nocloud CIDATA ISO (cloud-init).
#
# Never bakes the key into the qcow2. Never writes the RKE2 token into cidata.
#
# Proxmox 8.x upload API accepts content=iso|vztmpl|import but NOT snippets, so
# we ship user-data as a small cidata ISO on ide3. Sticky IPs use Proxmox's own
# cloud-init drive (ide2) + ipconfig0 — not nocloud network-config.
#
#   ./scripts/proxmox-age-cloudinit.sh           # write local user-data only (age key)
#   ./scripts/proxmox-age-cloudinit.sh 200 201  # build ISO, upload, attach
#
# Golden agent clones (identityMode = cloud-init):
#   PROXMOX_HOSTNAME_210=agent7
#   PROXMOX_JOIN_URL_210=https://192.168.1.29:9345   # optional; defaults from topology VIP
#   PROXMOX_IPCONFIG_210='ip=192.168.1.40/24,gw=192.168.1.1'
#   ./scripts/proxmox-age-cloudinit.sh 210
#
# Env: same PROXMOX_* / PROXMOX_ENV as proxmox-import.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGE_KEY="${SOPS_AGE_KEY_FILE:-$ROOT/secrets/age.key}"
WORK="${PROXMOX_AGE_WORKDIR:-$ROOT/../tmp-rke2nixos/age-cloudinit}"
USERDATA_NAME="${PROXMOX_AGE_USERDATA_NAME:-rke2nixos-age-userdata.yaml}"

load_proxmox_env() {
  if [[ -n "${PROXMOX_HOST:-}" && -n "${PROXMOX_TOKEN_ID:-}" && -n "${PROXMOX_TOKEN_SECRET:-}" ]]; then
    return 0
  fi
  local candidates=()
  [[ -n "${PROXMOX_ENV:-}" ]] && candidates+=("${PROXMOX_ENV}")
  candidates+=(
    "$ROOT/rke2nixos-proxmox.env"
    "$ROOT/../tmp-rke2nixos/rke2nixos-proxmox.env"
    "$HOME/rke2nixos-proxmox.env"
    "$HOME/.config/rke2nixos/proxmox.env"
  )
  local f
  for f in "${candidates[@]}"; do
    if [[ -f "$f" ]]; then
      echo "Loading Proxmox env from $f"
      set -a
      set +H
      # shellcheck source=/dev/null
      source "$f"
      set +a
      return 0
    fi
  done
  return 1
}

default_join_url() {
  if [[ -n "${PROXMOX_JOIN_URL:-}" ]]; then
    printf '%s' "$PROXMOX_JOIN_URL"
    return 0
  fi
  # Prefer cluster VIP from topology.nix when available.
  if [[ -f "$ROOT/hosts/proxmox/topology.nix" ]] && command -v nix >/dev/null 2>&1; then
    local vip
    vip="$(
      nix eval --impure --raw --expr "
        let t = import $ROOT/hosts/proxmox/topology.nix;
        in if t.clusterVip != \"\" then t.clusterVip else t.bootstrapHost
      " 2>/dev/null || true
    )"
    if [[ -n "$vip" ]]; then
      printf 'https://%s:9345' "$vip"
      return 0
    fi
  fi
  printf '%s' "https://192.168.1.29:9345"
}

write_userdata() {
  local out="$1"
  local hostname="${2:-}"
  local join_url="${3:-}"

  {
    cat <<'HDR'
#cloud-config
# Generated by scripts/proxmox-age-cloudinit.sh — do not commit.
# Never include the RKE2 token here (age key → sops-nix only).
write_files:
  - path: /var/lib/sops-nix/key.txt
    owner: root:root
    permissions: '0600'
    content: |
HDR
    sed 's/^/      /' "$AGE_KEY"

    if [[ -n "$hostname" ]]; then
      cat <<EOF
  - path: /run/rke2nixos/node-name
    owner: root:root
    permissions: '0644'
    content: |
      ${hostname}
EOF
    fi

    if [[ -n "$join_url" ]]; then
      cat <<EOF
  - path: /run/rke2nixos/join-url
    owner: root:root
    permissions: '0644'
    content: |
      ${join_url}
EOF
    fi

    cat <<'FOOT'

runcmd:
  - mkdir -p /var/lib/sops-nix /run/rke2nixos
  - chmod 700 /var/lib/sops-nix
  - chmod 600 /var/lib/sops-nix/key.txt
  # Materialize /run/secrets after the age key is in place (sops-nix).
  - /run/current-system/activate
FOOT
  } >"$out"
}

[[ -f "$AGE_KEY" ]] || {
  echo "error: age key not found: $AGE_KEY" >&2
  exit 1
}
if [[ ! -s "$AGE_KEY" ]] || ! grep -q 'AGE-SECRET-KEY-' "$AGE_KEY"; then
  echo "error: $AGE_KEY looks empty or invalid (need AGE-SECRET-KEY-…)" >&2
  exit 1
fi

mkdir -p "$WORK"
USERDATA="$WORK/$USERDATA_NAME"
write_userdata "$USERDATA"
echo "Wrote $USERDATA (age key only)"

if [[ $# -eq 0 ]]; then
  echo "No VMIDs given — local user-data only."
  echo "Attach later: $0 <vmid> [vmid…]"
  echo "Golden: set PROXMOX_HOSTNAME_<vmid> (+ optional PROXMOX_JOIN_URL_<vmid>) before attach."
  exit 0
fi

load_proxmox_env || true
HOST="${PROXMOX_HOST:-}"
PORT="${PROXMOX_PORT:-8006}"
NODE="${PROXMOX_NODE:-}"
ISO_STORAGE="${PROXMOX_SNIPPET_STORAGE:-${PROXMOX_UPLOAD_STORAGE:-local}}"
DISK_STORAGE="${PROXMOX_STORAGE:-local-lvm}"

missing=()
[[ -n "${PROXMOX_HOST:-}" ]] || missing+=("PROXMOX_HOST")
[[ -n "${PROXMOX_TOKEN_ID:-}" ]] || missing+=("PROXMOX_TOKEN_ID")
[[ -n "${PROXMOX_TOKEN_SECRET:-}" && "${PROXMOX_TOKEN_SECRET}" != REPLACE* ]] || missing+=("PROXMOX_TOKEN_SECRET")
((${#missing[@]} == 0)) || {
  echo "error: missing Proxmox API vars: ${missing[*]}" >&2
  exit 1
}

parse_ipconfig() {
  local raw="$1"
  IPADDR=""; GW=""
  [[ -z "$raw" ]] && return 1
  local part
  IFS=',' read -ra parts <<<"$raw"
  for part in "${parts[@]}"; do
    case "$part" in
      ip=*) IPADDR="${part#ip=}" ;;
      gw=*) GW="${part#gw=}" ;;
    esac
  done
  [[ -n "$IPADDR" ]]
}

curl_opts=(-sS -H "Authorization: PVEAPIToken=${PROXMOX_TOKEN_ID}=${PROXMOX_TOKEN_SECRET}")
[[ "${PROXMOX_INSECURE:-0}" == "1" ]] && curl_opts+=(-k)

curl_pve() {
  local method="$1" path="$2"
  shift 2
  curl "${curl_opts[@]}" -X "$method" "https://${HOST}:${PORT}${path}" "$@"
}

wait_task() {
  local upid="${1:-}"
  [[ -n "$upid" && "$upid" != "null" ]] || return 0
  local enc status st exitstatus task_node
  enc="$(printf '%s' "$upid" | jq -sRr @uri)"
  task_node="$(echo "$upid" | cut -d: -f2)"
  local i
  for i in $(seq 1 300); do
    status="$(curl_pve GET "/api2/json/nodes/${task_node}/tasks/${enc}/status")"
    st="$(echo "$status" | jq -r '.data.status // empty')"
    if [[ "$st" == "stopped" ]]; then
      exitstatus="$(echo "$status" | jq -r '.data.exitstatus // empty')"
      [[ "$exitstatus" == "OK" ]] && return 0
      echo "error: task failed ($exitstatus): $upid" >&2
      return 1
    fi
    sleep 1
  done
  echo "error: timeout waiting for $upid" >&2
  return 1
}

pick_node() {
  [[ -n "$NODE" ]] && return 0
  NODE="$(curl_pve GET "/api2/json/nodes" | jq -r '.data[0].node')"
  [[ -n "$NODE" && "$NODE" != "null" ]] || {
    echo "error: could not pick Proxmox node" >&2
    exit 1
  }
}

vm_node() {
  local vmid="$1"
  curl_pve GET "/api2/json/cluster/resources?type=vm" \
    | jq -r --argjson id "$vmid" '.data[]? | select(.vmid == $id) | .node' | head -1
}

pick_node

for vmid in "$@"; do
  vnode="$(vm_node "$vmid")"
  [[ -n "$vnode" && "$vnode" != "null" ]] || vnode="$NODE"

  hostname_var="PROXMOX_HOSTNAME_${vmid}"
  join_var="PROXMOX_JOIN_URL_${vmid}"
  hostname="${!hostname_var:-}"
  join_url="${!join_var:-}"
  if [[ -n "$hostname" && -z "$join_url" ]]; then
    join_url="$(default_join_url)"
  fi

  meta="$WORK/meta-data-${vmid}"
  iso="$WORK/rke2nixos-age-${vmid}.iso"
  ud="$WORK/user-data-${vmid}"
  write_userdata "$ud" "$hostname" "$join_url"

  # Unique instance-id so re-attach re-runs cloud-init.
  {
    printf 'instance-id: rke2nixos-%s-%s\n' "$vmid" "${PROXMOX_AGE_INSTANCE_SUFFIX:-$(date +%s)}"
    if [[ -n "$hostname" ]]; then
      printf 'local-hostname: %s\n' "$hostname"
    fi
  } >"$meta"

  stage="$WORK/stage-${vmid}"
  rm -rf "$stage"
  mkdir -p "$stage"
  cp "$ud" "$stage/user-data"
  cp "$meta" "$stage/meta-data"

  echo "Building cidata ISO for VM $vmid…"
  [[ -n "$hostname" ]] && echo "  hostname=$hostname join_url=$join_url"
  if command -v cloud-localds >/dev/null 2>&1; then
    cloud-localds "$iso" "$stage/user-data" "$stage/meta-data"
  elif command -v genisoimage >/dev/null 2>&1 || command -v mkisofs >/dev/null 2>&1; then
    mkiso="$(command -v genisoimage || command -v mkisofs)"
    (cd "$stage" && "$mkiso" -output "$iso" -volid cidata -joliet -rock .)
  elif command -v xorriso >/dev/null 2>&1; then
    xorriso -as mkisofs -o "$iso" -V cidata -J -R "$stage"
  else
    echo "error: need cloud-localds, genisoimage, mkisofs, or xorriso" >&2
    exit 1
  fi

  remote_name="rke2nixos-age-${vmid}.iso"
  echo "Uploading $remote_name → ${ISO_STORAGE} (iso) on ${vnode}…"
  up_json="$(
    curl "${curl_opts[@]}" -X POST \
      "https://${HOST}:${PORT}/api2/json/nodes/${vnode}/storage/${ISO_STORAGE}/upload" \
      -F "content=iso" \
      -F "filename=@${iso};filename=${remote_name}"
  )"
  if echo "$up_json" | jq -e '.message != null and .data == null' >/dev/null 2>&1; then
    echo "error: ISO upload failed: $(echo "$up_json" | jq -r .message)" >&2
    echo "$up_json" | jq . >&2
    exit 1
  fi
  wait_task "$(echo "$up_json" | jq -r '.data // empty')"

  volid="${ISO_STORAGE}:iso/${remote_name}"
  # ide3 = age cidata ISO; ide2 = Proxmox cloud-init drive for sticky ipconfig0
  args=(--data-urlencode "ide3=${volid},media=cdrom")
  ipcfg_var="PROXMOX_IPCONFIG_${vmid}"
  if parse_ipconfig "${!ipcfg_var:-}"; then
    args+=(
      --data-urlencode "ide2=${DISK_STORAGE}:cloudinit"
      --data-urlencode "ipconfig0=${!ipcfg_var}"
    )
    [[ -n "$GW" ]] && args+=(--data-urlencode "nameserver=${GW}")
    echo "  Proxmox ipconfig0=${!ipcfg_var}"
  fi

  echo "Attaching age ISO on ide3 (+ optional Proxmox cloudinit IP) for VM $vmid ($vnode)…"
  cfg="$(curl_pve PUT "/api2/json/nodes/${vnode}/qemu/${vmid}/config" "${args[@]}")"
  wait_task "$(echo "$cfg" | jq -r '.data // empty')"
  echo "OK: VM $vmid"
done

echo
echo "Age key → /var/lib/sops-nix/key.txt on first cloud-init boot."
echo "Golden: /run/rke2nixos/{node-name,join-url} when PROXMOX_HOSTNAME_<vmid> is set."
echo "Start VMs after attach (cold boot preferred)."
